# This is a basic workflow to help you get started with Actions

name: AutoBuild

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
    
      - name: Installer Java 11
        uses: actions/setup-java@v2.0.0
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Installer NodeJS 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Modifier le .env de Nebula
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "__JAVAEX__"
          replace: "$(which java)"
          include: "Nebula/.env"

      - name: Modifier le .env de Nebula
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "__WORKSPACE__"
          replace: "/home/runner/work/Distribution/Distribution"
          include: "Nebula/.env"
          
      - name: Lister les dossiers
        run: |
          ls -l
          echo "$GITHUB_WORKSPACE"
          pwd
          
      - name: Installer Nebula
        working-directory: ./Nebula
        run: npm i
        
      - name: Générer le distribution final
        working-directory: ./Nebula
        run: npm run start -- generate distro
        
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: 'chore: autobuild ${date}'
